#Kafka configuration
kafka.bootstrap.servers=localhost:9094
kafka-streams.consumer.session.timeout.ms=10000
kafka-streams.consumer.heartbeat.interval.ms=1000
kafka-streams.commit.interval.ms=1000
kafka-streams.metadata.max.age.ms=500
kafka-streams.auto.offset.reset=earliest
kafka-streams.metrics.recording.level=INFO
kafka-streams.poll.ms=100

influxdb.connectionUrl=http://localhost:8086
influxdb.token=ZYj1tfkL2sQ5AFQq9-83AqLFfYZhVC1hW0S23ZmmT9gwbqtF9JKpJLyWrBAiCLt7EDaEhaiAUm7_bmdLe-TfMQ==
influxdb.orgId=flomaestro
influxdb.data.bucketId=data