takt.engine.keyvaluestoretype=persistent

#Kafka configuration
kafka.bootstrap.servers=db-kafka-ams3-81783-do-user-18178302-0.k.db.ondigitalocean.com:25073
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=SCRAM-SHA-256
kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="doadmin" password="AVNS_j8bUN_EZYiWTDMwM4lM";
kafka.ssl.endpoint.identification.algorithm=
kafka.ssl.truststore.type=jks
kafka.ssl.truststore.location=/Users/erichendriks/IdeaProjects/bpmnMeister/takt-monitoring/config/truststore.jks
kafka.ssl.truststore.password=changeit
kafka.num.stream.threads=3
kafka.consumer.poll.ms=100
kafka-streams.consumer.session.timeout.ms=10000
kafka-streams.consumer.heartbeat.interval.ms=1000
kafka-streams.commit.interval.ms=1000
kafka-streams.metadata.max.age.ms=500
kafka-streams.auto.offset.reset=latest
kafka-streams.metrics.recording.level=INFO
kafka-streams.poll.ms=100

influxdb.connectionUrl=http://localhost:8086
influxdb.token=uu9yrrfaTkIHqjait-PtgxnTZWzxgVBe3YYbyE__-VT_KP5amviPzRpAG0Hlnm7DGYYWqFYqEyi9ySAW8s4EfQ==
influxdb.orgId=Flomaestro
influxdb.data.bucketId=data