#Kafka configuration
kafka.bootstrap.servers=localhost:9094
kafka-streams.consumer.session.timeout.ms=10000
kafka-streams.consumer.heartbeat.interval.ms=1000
kafka-streams.commit.interval.ms=1000
kafka-streams.metadata.max.age.ms=500
kafka-streams.auto.offset.reset=earliest
kafka-streams.metrics.recording.level=INFO
kafka-streams.poll.ms=100

influxdb.connectionUrl=http://localhost:8086
influxdb.token=hsEVLi86M9XiKZ-Y860YxDwUQabCBMZ97BzgjW1BxbVojIlhwIhWLmpkz26X3RTm_6QNVZ6BbjTzo7-BJrzZUQ==
influxdb.orgId=flomaestro
influxdb.data.bucketId=data