# Configure the Kafka broker location
quarkus.http.port=8079
%local.kafka.bootstrap.servers=localhost:9092
%confluent.kafka.bootstrap.servers=pkc-7xoy1.eu-central-1.aws.confluent.cloud:9092

kafka.topic.replication-factor=1
%confluent.kafka.topic.replication-factor=3

# Required connection configs for Kafka producer, consumer, and admin
%confluent.kafka.sasl.mechanism=PLAIN
%confluent.kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='MGOSZQGI27P5UBEZ' password='iQfXj6t4pTdVHcBp95lJLqMedziHFaQfgqU0D6q0B4UFrdPvrKipIMn+bzUix5N9';
%confluent.kafka.security.protocol=SASL_SSL

# Best practice for higher availability in Apache Kafka clients prior to 3.0
%confluent.kafka.session.timeout.ms=10000

nl.flommaestro.takt.tenant=${tenant}
nl.flommaestro.takt.namespace=${namespace}