# Configure the Kafka broker location
quarkus.http.port=8079
%local.kafka.bootstrap.servers=localhost:9094

kafka.topic.replication-factor=1

# Required connection configs for Kafka producer, consumer, and admin
%digitalocean.kafka.bootstrap.servers=db-kafka-ams3-81783-do-user-18178302-0.k.db.ondigitalocean.com:25073
%digitalocean.kafka.security.protocol=SASL_SSL
%digitalocean.kafka.sasl.mechanism=SCRAM-SHA-256
%digitalocean.kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="doadmin" password="AVNS_j8bUN_EZYiWTDMwM4lM";
%digitalocean.kafka.ssl.endpoint.identification.algorithm=
%digitalocean.kafka.ssl.truststore.type=jks
%digitalocean.kafka.ssl.truststore.location=/Users/erichendriks/IdeaProjects/bpmnMeister/takt-admin/truststore.jks
%digitalocean.kafka.ssl.truststore.password=changeit

# Required connection configs for Kafka producer, consumer, and admin
%redpanda.kafka.bootstrap.servers=ctve1uqdt8sjp3bod5u0.any.eu-central-1.mpx.prd.cloud.redpanda.com:9092
%redpanda.kafka.security.protocol=SASL_SSL
%redpanda.kafka.sasl.mechanism=SCRAM-SHA-256
%redpanda.kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="flomaestro" password="ENgEMEEmfsp15eKXnYdGujA4UTKISq";
%redpanda.kafka.ssl.endpoint.identification.algorithm=
%redpanda.kafka.ssl.truststore.type=jks

nl.flommaestro.takt.tenant=${tenant}
nl.flommaestro.takt.namespace=${namespace}