# Configure the Kafka broker location
kafka.bootstrap.servers=localhost:9092
quarkus.http.port=8081
quarkus.scheduler.start-mode=forced

mp.messaging.incoming.recurring.topic=recurring-schedule-commands
mp.messaging.incoming.recurring.group.id=recurring-command-scheduler
mp.messaging.incoming.recurring.connector=smallrye-kafka

mp.messaging.outgoing.outgoing.connector=smallrye-kafka
mp.messaging.outgoing.outgoing.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.outgoing.key.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.one-time-out.connector=smallrye-kafka
mp.messaging.outgoing.one-time-out.value.serializer=org.apache.kafka.common.serialization.VoidSerializer
