# Configure the Kafka broker location
quarkus.http.port=8078
quarkus.kafka-streams.topics=${tenant}.${namespace}.processing-statistics

takt.engine.tenant=${tenant}
takt.engine.namespace=${namespace}
