# Configure the Kafka broker location
quarkus.http.port=8078
quarkus.kafka-streams.topics=${tenant}.${namespace}.processing-statistics

nl.flommaestro.takt.tenant=${tenant}
nl.flommaestro.takt.namespace=${namespace}
