# Configure the Kafka broker location
kafka.bootstrap.servers=localhost:9092
quarkus.http.port=8080

mp.messaging.incoming.trigger-incoming.connector=smallrye-kafka
mp.messaging.incoming.trigger-incoming.topic=trigger-topic
mp.messaging.incoming.trigger-incoming.auto.offset.reset=earliest

mp.messaging.incoming.process-definition-xml-incoming.connector=smallrye-kafka
mp.messaging.incoming.process-definition-xml-incoming.topic=process-definition-xml-incoming-topic
mp.messaging.incoming.process-definition-xml-incoming.auto.offset.reset=earliest

mp.messaging.outgoing.trigger-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.trigger-outgoing.topic=trigger-topic

mp.messaging.outgoing.recurring-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.recurring-outgoing.topic=recurring-schedule-commands


mp.messaging.outgoing.task-schedules-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.task-schedules-outgoing.topic=task-schedules
mp.messaging.outgoing.task-schedules-outgoing.key.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.task-schedules-outgoing.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

quarkus.mongodb.connection-string = mongodb://localhost:27017
quarkus.mongodb.uuid-representation = java-legacy
quarkus.mongodb.database = bpmnMeister

