# Configure the Kafka broker location
kafka.bootstrap.servers=localhost:9092
quarkus.http.port=8080
quarkus.scheduler.start-mode=forced

mp.messaging.incoming.process-definition-xml-incoming.connector=smallrye-kafka
mp.messaging.incoming.process-definition-xml-incoming.topic=process-definition-xml-incoming-topic
mp.messaging.incoming.process-definition-xml-incoming.auto.offset.reset=earliest

mp.messaging.incoming.trigger-incoming.connector=smallrye-kafka
mp.messaging.incoming.trigger-incoming.topic=trigger-topic
mp.messaging.incoming.trigger-incoming.auto.offset.reset=earliest

mp.messaging.incoming.one-time.topic=one-time-schedule-commands
mp.messaging.incoming.one-time.group.id=one-time-command-scheduler
mp.messaging.incoming.one-time.connector=smallrye-kafka

mp.messaging.incoming.recurring.topic=recurring-schedule-commands
mp.messaging.incoming.recurring.group.id=recurring-command-scheduler
mp.messaging.incoming.recurring.connector=smallrye-kafka

mp.messaging.incoming.fixed-rate.topic=fixed-rate-schedule-commands
mp.messaging.incoming.fixed-rate.group.id=fixed-rate-command-scheduler
mp.messaging.incoming.fixed-rate.connector=smallrye-kafka

mp.messaging.outgoing.outgoing.connector=smallrye-kafka
mp.messaging.outgoing.outgoing.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.outgoing.key.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.one-time-out.connector=smallrye-kafka
mp.messaging.outgoing.one-time-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.one-time-out.value.serializer=org.apache.kafka.common.serialization.VoidSerializer

mp.messaging.outgoing.fixed-rate-out.connector=smallrye-kafka
mp.messaging.outgoing.fixed-rate-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.fixed-rate-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.trigger-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.trigger-outgoing.topic=trigger-topic

mp.messaging.outgoing.recurring-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.recurring-outgoing.topic=recurring-schedule-commands
mp.messaging.outgoing.recurring-outgoing.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.recurring-outgoing.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.one-time-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.one-time-outgoing.topic=one-time-schedule-commands
mp.messaging.outgoing.one-time-outgoing.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.one-time-outgoing.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.fixed-rate-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.fixed-rate-outgoing.topic=fixed-rate-schedule-commands
mp.messaging.outgoing.fixed-rate-outgoing.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.fixed-rate-outgoing.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

quarkus.mongodb.connection-string = mongodb://localhost:27017
quarkus.mongodb.uuid-representation = java-legacy
quarkus.mongodb.database = bpmnMeister

