%dev.kafka.bootstrap.servers=localhost:9092
%dev.quarkus.kafka-streams.bootstrap-servers=localhost:9092
%test.quarkus.kafka.devservices.enabled=false
%test.quarkus.arc.selected-alternatives=nl.qunit.bpmnmeister.engine.pd.InMemoryKeyValueStoreSupplier

quarkus.http.port=8081
quarkus.kafka-streams.application-server=${hostname}:8081
quarkus.kafka-streams.topics=process-definition-parsed-topic,process-definition-activation-topic,process-instance-start-command-topic,process-definition-xml-topic,schedule-commands,process-instance-trigger-topic,external-task-trigger-topic,process-migration-topic
kafka-streams.consumer.session.timeout.ms=10000
kafka-streams.consumer.heartbeat.interval.ms=1000

%test.mp.messaging.outgoing.process-instance-trigger-outgoing.connector=smallrye-kafka
%test.mp.messaging.outgoing.process-instance-trigger-outgoing.topic=process-instance-trigger-topic
%test.mp.messaging.outgoing.process-instance-trigger-outgoing.key.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
%test.mp.messaging.outgoing.process-instance-trigger-outgoing.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

%test.mp.messaging.outgoing.process-instance-start-command-outgoing.connector=smallrye-kafka
%test.mp.messaging.outgoing.process-instance-start-command-outgoing.topic=process-instance-start-command-topic
%test.mp.messaging.outgoing.process-instance-start-command-outgoing.key.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
%test.mp.messaging.outgoing.process-instance-start-command-outgoing.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

%test.mp.messaging.incoming.external-task-trigger-incoming.connector=smallrye-kafka
%test.mp.messaging.incoming.external-task-trigger-incoming.topic=external-task-trigger-topic
%test.mp.messaging.incoming.external-task-trigger-incoming.key.deserialized=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
%test.mp.messaging.incoming.external-task-trigger-incoming.group.id=external-task-trigger-group

%test.mp.messaging.incoming.process-instance-incoming.connector=smallrye-kafka
%test.mp.messaging.incoming.process-instance-incoming.topic=process-instance-topic
%test.mp.messaging.incoming.process-instance-incoming.key.deserialized=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
%test.mp.messaging.incoming.process-instance-incoming.group.id=external-task-trigger-group


# pass-through options
kafka-streams.cache.max.bytes.buffering=10240
kafka-streams.commit.interval.ms=1000
kafka-streams.metadata.max.age.ms=500
kafka-streams.auto.offset.reset=earliest
kafka-streams.metrics.recording.level=DEBUG
kafka-streams.poll.ms=10
