takt.engine.keyvaluestoretype=inmemory
takt.engine.topic.replication-factor=2

#Kafka configuration
kafka.bootstrap.servers=db-kafka-ams3-87954-do-user-251588-0.e.db.ondigitalocean.com:25073
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=SCRAM-SHA-256
kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="doadmin" password="AVNS_ih_Jh-dJJfTORESYPpW";
kafka.ssl.endpoint.identification.algorithm=
kafka.ssl.truststore.type=jks
kafka.ssl.truststore.location=config/truststore.jks
kafka.ssl.truststore.password=changeit
kafka.num.stream.threads=3
kafka.consumer.poll.ms=100
kafka-streams.consumer.session.timeout.ms=10000
kafka-streams.consumer.heartbeat.interval.ms=1000
kafka-streams.commit.interval.ms=1000
kafka-streams.metadata.max.age.ms=500
kafka-streams.auto.offset.reset=latest
kafka-streams.metrics.recording.level=INFO
kafka-streams.poll.ms=100