taktx.engine.keyvaluestoretype=persistent
taktx.engine.topic.replication-factor=1
taktx.engine.topic.partitions=12

#Kafka configuration
kafka.bootstrap.servers=localhost:9092
kafka.num.stream.threads=3
kafka-streams.consumer.session.timeout.ms=10000
kafka-streams.consumer.heartbeat.interval.ms=1000
kafka-streams.commit.interval.ms=1000
kafka-streams.metadata.max.age.ms=500
kafka-streams.auto.offset.reset=latest
kafka-streams.metrics.recording.level=INFO
kafka-streams.poll.ms=100
