taktx.engine.keyvaluestoretype=inmemory

taktx.engine.topic.replication-factor=1
taktx.engine.topic.partitions=3
taktx.engine.namespace=namespace

#Kafka configuration
kafka.bootstrap.servers=localhost:9092
kafka.num.stream.threads=3

kafka-streams.consumer.session.timeout.ms=10000
kafka-streams.consumer.heartbeat.interval.ms=1000
kafka-streams.consumer.fetch.min.bytes=262144
kafka-streams.consumer.fetch.max.wait.ms=50
kafka-streams.consumer.max.partition.fetch.bytes=2097152
kafka-streams.consumer.max.poll.records=10000

kafka-streams.producer.batch.size=262144
kafka-streams.producer.linger.ms=50
kafka-streams.producer.compression.type=none
kafka-streams.producer.acks=all
kafka-streams.producer.enable.idempotence=true
kafka-streams.producer.max.in.flight.requests.per.connection=5

kafka-streams.commit.interval.ms=100
kafka-streams.metadata.max.age.ms=60000
kafka-streams.auto.offset.reset=latest
kafka-streams.metrics.recording.level=INFO
kafka-streams.poll.ms=50
