taktx.engine.keyvaluestoretype=inmemory

taktx.engine.topic.replication-factor=1
taktx.engine.topic.partitions=12
taktx.engine.tenant=tenant
taktx.engine.namespace=namespace
taktx.engine.broadcastInstanceUpdates=false

#Kafka configuration
kafka.bootstrap.servers=localhost:9092
kafka.num.stream.threads=12

kafka-streams.consumer.session.timeout.ms=10000
kafka-streams.consumer.heartbeat.interval.ms=1000
kafka-streams.commit.interval.ms=1000
kafka-streams.metadata.max.age.ms=500
kafka-streams.auto.offset.reset=latest
kafka-streams.metrics.recording.level=INFO
kafka-streams.poll.ms=100
replication.factor=3