bootstrap.servers=db-kafka-ams3-87954-do-user-251588-0.e.db.ondigitalocean.com:25073
security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-256
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="client" password="AVNS_ZETAs8YO2xxqPABj74u";
ssl.endpoint.identification.algorithm=
ssl.truststore.type=jks
ssl.truststore.location=/Users/erichendriks/IdeaProjects/TaktX-engine/taktx-engine/config/truststore.jks
ssl.truststore.password=changeit
