%test.quarkus.arc.selected-alternatives=nl.qunit.bpmnmeister.engine.pd.FixedClockProducer,nl.qunit.bpmnmeister.engine.pd.InMemoryKeyValueStoreSupplier

%dockerlocal.kafka.bootstrap.servers=host.docker.internal:9091
%dockerlocal.quarkus.kafka-streams.bootstrap-servers=host.docker.internal:9091

%local.kafka.bootstrap.servers=localhost:9092
%local.quarkus.kafka-streams.bootstrap-servers=localhost:9092

quarkus.kafka-streams.application-server=${injectedhost}:${injectedport}

quarkus.kafka-streams.application-id=engine3

%confluent.kafka.bootstrap.servers=pkc-7xoy1.eu-central-1.aws.confluent.cloud:9092
%confluent.quarkus.kafka-streams.bootstrap-servers=pkc-7xoy1.eu-central-1.aws.confluent.cloud:9092

# Required connection configs for Kafka producer, consumer, and admin
%confluent.kafka.sasl.mechanism=PLAIN
%confluent.kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='MGOSZQGI27P5UBEZ' password='iQfXj6t4pTdVHcBp95lJLqMedziHFaQfgqU0D6q0B4UFrdPvrKipIMn+bzUix5N9';
%confluent.kafka.security.protocol=SASL_SSL

# Best practice for higher availability in Apache Kafka clients prior to 3.0
%confluent.kafka.session.timeout.ms=10000
quarkus.kafka-streams.topics=${tenant}.${namespace}.definitions-topic,${tenant}.${namespace}.process-definition-parsed-topic,${tenant}.${namespace}.process-definition-activation-topic,,${tenant}.${namespace}.schedule-commands,${tenant}.${namespace}.process-instance-trigger-topic,${tenant}.${namespace}.external-task-trigger-topic
%test.quarkus.kafka-streams.topics=test_tenant.test_namespace.definitions-trigger-topic,test_tenant.test_namespace.process-definition-parsed-topic,test_tenant.test_namespace.process-definition-activation-topic,test_tenant.test_namespace.schedule-commands,test_tenant.test_namespace.process-instance-trigger-topic,test_tenant.test_namespace.external-task-trigger-topic

kafka-streams.consumer.session.timeout.ms=10000
kafka-streams.consumer.heartbeat.interval.ms=1000

quarkus.log.level=INFO
quarkus.swagger-ui.always-include=true
quarkus.http.cors=true

# pass-through options
statestore.cache.max.bytes=10240
kafka-streams.commit.interval.ms=1000
kafka-streams.metadata.max.age.ms=500
kafka-streams.auto.offset.reset=earliest
kafka-streams.metrics.recording.level=INFO
kafka-streams.poll.ms=10

nl.flommaestro.takt.tenant=${tenant}
nl.flommaestro.takt.namespace=${namespace}
%test.nl.flommaestro.takt.tenant=test_tenant
%test.nl.flommaestro.takt.namespace=test_namespace