%test.quarkus.arc.selected-alternatives=com.flomaestro.engine.pd.FixedClockProducer,com.flomaestro.engine.pd.InMemoryKeyValueStoreSupplier

quarkus.kafka-streams.application-server=${injectedhost}:${injectedport}
quarkus.kafka-streams.application-id=takt-engine

# Best practice for higher availability in Apache Kafka clients prior to 3.0
quarkus.kafka-streams.topics=${tenant}.${namespace}.definitions-trigger-topic,${tenant}.${namespace}.process-definition-activation-topic,${tenant}.${namespace}.schedule-commands,${tenant}.${namespace}.process-instance-trigger-topic,${tenant}.${namespace}.external-task-trigger-topic
%test.quarkus.kafka-streams.topics=test_tenant.test_namespace.definitions-trigger-topic,test_tenant.test_namespace.process-definition-activation-topic,test_tenant.test_namespace.schedule-commands,test_tenant.test_namespace.process-instance-trigger-topic,test_tenant.test_namespace.external-task-trigger-topic

quarkus.log.level=INFO
quarkus.swagger-ui.always-include=true
quarkus.http.cors=true

nl.flommaestro.takt.tenant=${tenant}
nl.flommaestro.takt.namespace=${namespace}
%test.nl.flommaestro.takt.tenant=test_tenant
%test.nl.flommaestro.takt.namespace=test_namespace
