#
# /*
#  * TaktX - A high-performance BPMN engine
#  * Copyright (c) 2025 TaktX B.V. All rights reserved.
#  * This file is part of TaktX, licensed under the TaktX Business Source License v1.0.
#  * Free use is permitted with up to 3 Kafka partitions. See LICENSE file for details.
#  * For commercial use or more partitions and features, contact [info@taktx.io] or [https://www.taktx.io/contact].
#  */
#

%test.quarkus.arc.selected-alternatives=com.flomaestro.engine.generic.FixedClockProducer
takt.engine.keyvaluestoretype=inmemory
quarkus.kafka-streams.application-server=${injectedhost}:${injectedport}
quarkus.kafka-streams.application-id=takt-engine

# Best practice for higher availability in Apache Kafka clients prior to 3.0
quarkus.kafka-streams.topics=${tenant}.${namespace}.definitions-trigger,${tenant}.${namespace}.process-definition-activation,${tenant}.${namespace}.schedule-commands,${tenant}.${namespace}.process-instance-trigger,${tenant}.${namespace}.instance-update
%test.quarkus.kafka-streams.topics=test_tenant.test_namespace.definitions-trigger,test_tenant.test_namespace.process-definition-activation,test_tenant.test_namespace.schedule-commands,test_tenant.test_namespace.process-instance-trigger,test_tenant.test_namespace.instance-update

quarkus.log.level=INFO
quarkus.swagger-ui.always-include=true
quarkus.http.cors=true

%test.nl.flommaestro.takt.partitions=3

%test.takt.engine.tenant=test_tenant
%test.takt.engine.namespace=test_namespace
%test.takt.engine.topic.replication-factor=1
%test.takt.engine.topic.partitions=5

quarkus.micrometer.binder-enabled-default=true
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.system=true
quarkus.micrometer.binder.kafka=true
quarkus.micrometer.export.prometheus.enabled=true