# Configure the Kafka broker location
quarkus.http.port=8081

deployer.kafka.bootstrap.servers=localhost:9092

%confluent.deployer.kafka.bootstrap.servers=pkc-7xoy1.eu-central-1.aws.confluent.cloud:9092

# Required connection configs for Kafka producer, consumer, and admin
%confluent.deployer.kafka.sasl.mechanism=PLAIN
%confluent.deployer.kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='MGOSZQGI27P5UBEZ' password='iQfXj6t4pTdVHcBp95lJLqMedziHFaQfgqU0D6q0B4UFrdPvrKipIMn+bzUix5N9';
%confluent.deployer.kafka.security.protocol=SASL_SSL
deployer.kafka.sasl.mechanism=
deployer.kafka.sasl.jaas.config=
deployer.kafka.security.protocol=

# Best practice for higher availability in Apache Kafka clients prior to 3.0
%confluent.kafka.session.timeout.ms=10000
