# Configure the Kafka broker location
quarkus.http.port=8080
kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.process-definition-xml-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.process-definition-xml-outgoing.topic=process-definition-xml-topic

mp.messaging.outgoing.process-instance-start-command-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.process-instance-start-command-outgoing.topic=process-instance-start-command-topic
mp.messaging.outgoing.process-instance-start-command-outgoing.key.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
#
#mp.messaging.incoming.process-definition-parsed-incoming.connector=smallrye-kafka
#mp.messaging.incoming.process-definition-parsed-incoming.topic=process-definition-parsed-topic

mp.messaging.incoming.external-task-trigger-incoming.connector=smallrye-kafka
mp.messaging.incoming.external-task-trigger-incoming.topic=external-task-trigger-topic

