# Configure the Kafka broker location
quarkus.http.port=8080
%dev.kafka.bootstrap.servers=localhost:9092
%confluent.kafka.bootstrap.servers=pkc-7xoy1.eu-central-1.aws.confluent.cloud:9092

# Required connection configs for Kafka producer, consumer, and admin
%confluent.kafka.sasl.mechanism=PLAIN
%confluent.kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='HDU6QPRRNN53CDRK' password='QCWctdwnx3Fh9XikXf2YMZ0sKNUCuH04WCiKjzWNB+ues1fLvmrozIjcCjHWFzvk';
%confluent.kafka.security.protocol=SASL_SSL

# Best practice for higher availability in Apache Kafka clients prior to 3.0
%confluent.kafka.session.timeout.ms=10000

mp.messaging.outgoing.process-definition-xml-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.process-definition-xml-outgoing.topic=process-definition-xml-topic

mp.messaging.outgoing.process-instance-start-command-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.process-instance-start-command-outgoing.topic=definitions-topic
mp.messaging.outgoing.process-instance-start-command-outgoing.key.serializer=org.apache.kafka.common.serialization.StringSerializer
#
#mp.messaging.incoming.process-definition-parsed-incoming.connector=smallrye-kafka
#mp.messaging.incoming.process-definition-parsed-incoming.topic=process-definition-parsed-topic

mp.messaging.incoming.external-task-trigger-incoming.connector=smallrye-kafka
mp.messaging.incoming.external-task-trigger-incoming.topic=external-task-trigger-topic
mp.messaging.incoming.external-task-trigger-incoming.key.deserialized=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.external-task-response-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.external-task-response-outgoing.topic=process-instance-trigger-topic
mp.messaging.outgoing.external-task-response-outgoing.key.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

