# Configure the Kafka broker location
quarkus.http.port=8081

nl.flommaestro.takt.tenant=${tenant}
nl.flommaestro.takt.namespace=${namespace}

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
