# Configure the Kafka broker location
quarkus.http.port=8081

takt.engine.tenant=${tenant}
takt.engine.namespace=${namespace}

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
