# Configure the Kafka broker location
kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.trigger-outgoing.connector=smallrye-kafka
mp.messaging.outgoing.trigger-outgoing.topic=trigger-topic

