# Configure the Kafka broker location
kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.process-definition-input.connector=smallrye-kafka
mp.messaging.outgoing.process-definition-input.topic=process-definition-input-topic

