# Configure the Kafka broker location
kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.process-instances.connector=smallrye-kafka
mp.messaging.outgoing.process-instances.key.serializer=org.apache.kafka.common.serialization.UUIDSerializer
mp.messaging.outgoing.process-instances.value.serializer=org.apache.kafka.common.serialization.StringSerializer

