#
# TaktX - A high-performance BPMN engine
# Copyright (c) 2025 Eric Hendriks All rights reserved.
# TaktX - A high-performance BPMN engine
# Copyright (c) 2025 Eric Hendriks
# Licensed under the Apache License, Version 2.0 - http://www.apache.org/licenses/LICENSE-2.0
#

# Native image configuration for MapStruct generated classes
Args = --initialize-at-build-time=io.taktx.engine.pi.ProcessInstanceMapperImpl \
       --initialize-at-build-time=io.taktx.engine.pi.DtoMapperImpl \
       --enable-all-security-services \
       --allow-incomplete-classpath \
       --report-unsupported-elements-at-runtime
